//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2.DreamFitness.App_Start
{


    public partial class Findfood
    {
        protected global::System.Web.UI.WebControls.DataList DataList1;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

    }
}
